# Generated by Django 2.2.5 on 2019-09-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20190925_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ciry',
            new_name='city',
        ),
    ]
